services:
    Drjele\DoctrineEncrypt\Encryptor\AbstractEncryptor:
        arguments:
            $salt: '%drjele_doctrine_encrypt.salt%'

    Drjele\DoctrineEncrypt\Encryptor\AES256Encryptor:
        parent: Drjele\DoctrineEncrypt\Encryptor\AbstractEncryptor
