services:
    Drjele\DoctrineEncrypt\Encryptor\AbstractEncryptor:
        abstract: true
        arguments:
            $salt: '%drjele_doctrine_encrypt.salt%'

    Drjele\DoctrineEncrypt\Encryptor\AES256Encryptor:
        parent: Drjele\DoctrineEncrypt\Encryptor\AbstractEncryptor

    Drjele\DoctrineEncrypt\Command\AbstractCommand:
        abstract: true

    Drjele\DoctrineEncrypt\Command\AbstractDatabaseCommand:
        abstract: true
        parent: Drjele\DoctrineEncrypt\Command\AbstractCommand
        arguments:
            $managerRegistry: '@Doctrine\Persistence\ManagerRegistry'

    Drjele\DoctrineEncrypt\Command\DatabaseEncryptCommand:
        parent: Drjele\DoctrineEncrypt\Command\AbstractDatabaseCommand
        tags:
            - { name: 'console.command' }

    Drjele\DoctrineEncrypt\Command\DatabaseDecryptCommand:
        parent: Drjele\DoctrineEncrypt\Command\AbstractDatabaseCommand
        tags:
            - { name: 'console.command' }
