services:
    Drjele\Doctrine\Encrypt\Encryptor\AbstractEncryptor:
        abstract: true
        arguments:
            $salt: '%drjele_doctrine_encrypt.salt%'

    Drjele\Doctrine\Encrypt\Encryptor\AES256Encryptor:
        parent: Drjele\Doctrine\Encrypt\Encryptor\AbstractEncryptor
        tags:
            - {name: 'drjele.doctrine.encryptor'}

    Drjele\Doctrine\Encrypt\Encryptor\FakeEncryptor:
        tags:
            - {name: 'drjele.doctrine.encryptor'}

    Drjele\Doctrine\Encrypt\Encryptor\AES256FixedEncryptor:
        parent: Drjele\Doctrine\Encrypt\Encryptor\AbstractEncryptor
        tags:
            - {name: 'drjele.doctrine.encryptor'}

    Drjele\Doctrine\Encrypt\Service\EncryptorFactory:
        public: true
        arguments:
            $encryptors: !tagged_iterator drjele.doctrine.encryptor

    Drjele\Doctrine\Encrypt\Command\AbstractDatabaseCommand:
        abstract: true
        arguments:
            $managerRegistry: '@Doctrine\Persistence\ManagerRegistry'
            $encryptorFactory: '@Drjele\Doctrine\Encrypt\Service\EncryptorFactory'
            $entityService: '@Drjele\Doctrine\Encrypt\Service\EntityService'

    Drjele\Doctrine\Encrypt\Command\DatabaseEncryptCommand:
        parent: Drjele\Doctrine\Encrypt\Command\AbstractDatabaseCommand
        tags:
            - {name: 'console.command'}

    Drjele\Doctrine\Encrypt\Command\DatabaseDecryptCommand:
        parent: Drjele\Doctrine\Encrypt\Command\AbstractDatabaseCommand
        tags:
            - {name: 'console.command'}

    Drjele\Doctrine\Encrypt\Service\EntityService:
        arguments:
            $managerRegistry: '@Doctrine\Persistence\ManagerRegistry'
            $encryptorFactory: '@Drjele\Doctrine\Encrypt\Service\EncryptorFactory'
