services:
    Drjele\DoctrineEncrypt\Service\AbstractEncryptorService:
        arguments:
            $salt: '%drjele_doctrine_encrypt.salt%'

    Drjele\DoctrineEncrypt\Service\EncryptorService:
        parent: Drjele\DoctrineEncrypt\Service\AbstractEncryptorService
